# Uncomment the next line to define a global platform for your project
platform :macos, '11.4'
pod 'SVGView'
target 'cue' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for cue

  target 'cueTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'cueUITests' do
    # Pods for testing
  end

end
